FROM debian:bookworm

WORKDIR /cluster-agent

# Install any runtime dependencies (if needed)
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY .tilt/cluster-agent .
COPY .tilt/rgkl/rgkl /usr/local/bin/rgkl

ENTRYPOINT ["/cluster-agent/cluster-agent", "-c", "/etc/kubetail/config.yaml"]
